-- RTB L5 Remaining Challenges Part 3 — orders 211,212,213,214,215,216,217,218,221,222,223,225,226,228
-- 2 challenges each (priority sets) = 28 total

-- ── ORDER 211: SWDFA501 Tailwind CSS Utility Classes ──────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-021100000001','00000000-0500-0000-0000-000000000211',1,
  'Tailwind Class Builder','Kubaka Amato ya Tailwind',
  'Tailwind CSS uses utility classes. Write `buildClasses(config)` that generates a class string from a config object:\n- `config.bg` → `"bg-${config.bg}"`\n- `config.text` → `"text-${config.text}"`\n- `config.p` → `"p-${config.p}"`\n- `config.rounded` → `"rounded"` (boolean flag)\n\nReturn all applicable classes joined by spaces.',
  'Tailwind CSS ikoresha amato ya utility. Andika `buildClasses` igira string ya amato.',
  'write_scratch','function buildClasses(config) {\n  const classes = [];\n  // Your code here\n}\n','',
  'Push each class if the key exists. For rounded, push "rounded" only if it is truthy.',
  'Sunika buri amato niba urupapuro ruriho.',
  '[{"assertion":"(function(){function buildClasses(c){const cl=[];if(c.bg)cl.push(`bg-${c.bg}`);if(c.text)cl.push(`text-${c.text}`);if(c.p!==undefined)cl.push(`p-${c.p}`);if(c.rounded)cl.push(''rounded'');return cl.join('' '');}return buildClasses({bg:''blue-500''}).includes(''bg-blue-500'');})()","description":"bg class generated"},{"assertion":"(function(){function buildClasses(c){const cl=[];if(c.text)cl.push(`text-${c.text}`);if(c.rounded)cl.push(''rounded'');return cl.join('' '');}return buildClasses({text:''white'',rounded:true}).includes(''rounded'');})()","description":"rounded added when true"},{"assertion":"(function(){function buildClasses(c){const cl=[];if(c.bg)cl.push(`bg-${c.bg}`);if(c.text)cl.push(`text-${c.text}`);return cl.join('' '');}return typeof buildClasses({bg:''red'',text:''white''})=== ''string'';})()","description":"Returns a string"},{"assertion":"(function(){function buildClasses(c){const cl=[];if(c.rounded)cl.push(''rounded'');return cl.join('' '');}return buildClasses({}).length===0;})()","description":"Empty config returns empty string"}]',
  'easy',160
),
(
  '00000000-0500-0000-0000-021100000002','00000000-0500-0000-0000-000000000211',2,
  'Responsive Breakpoint Checker','Gusuzuma Amaherezo y''Ibipimo',
  'Complete `getBreakpoint(widthPx)` that returns the Tailwind breakpoint name:\n- < 640 → `"xs"`\n- 640–767 → `"sm"`\n- 768–1023 → `"md"`\n- 1024–1279 → `"lg"`\n- ≥ 1280 → `"xl"`',
  'Uzuza `getBreakpoint` isubiza izina ry''amaherezo ya Tailwind.',
  'complete_code','function getBreakpoint(widthPx) {\n  if (widthPx < 640) return ____;\n  if (widthPx < 768) return ____;\n  if (widthPx < 1024) return ____;\n  if (widthPx < 1280) return ____;\n  return ____;\n}\n','',
  'The blanks in order: "xs", "sm", "md", "lg", "xl".',
  'Ibice mu murongo: "xs", "sm", "md", "lg", "xl".',
  '[{"assertion":"(function(){function getBreakpoint(w){if(w<640)return''xs'';if(w<768)return''sm'';if(w<1024)return''md'';if(w<1280)return''lg'';return''xl'';}return getBreakpoint(375)===''xs'';})()","description":"375px is xs"},{"assertion":"(function(){function getBreakpoint(w){if(w<640)return''xs'';if(w<768)return''sm'';if(w<1024)return''md'';if(w<1280)return''lg'';return''xl'';}return getBreakpoint(768)===''md'';})()","description":"768px is md"},{"assertion":"(function(){function getBreakpoint(w){if(w<640)return''xs'';if(w<768)return''sm'';if(w<1024)return''md'';if(w<1280)return''lg'';return''xl'';}return getBreakpoint(1440)===''xl'';})()","description":"1440px is xl"},{"assertion":"(function(){function getBreakpoint(w){if(w<640)return''xs'';if(w<768)return''sm'';if(w<1024)return''md'';if(w<1280)return''lg'';return''xl'';}return getBreakpoint(640)===''sm'';})()","description":"Exactly 640 is sm"}]',
  'easy',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDER 212: SWDFA501 Next.js & TypeScript ──────────────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-021200000001','00000000-0500-0000-0000-000000000212',1,
  'TypeScript Type Guard','Gusuzuma Ubwoko muri TypeScript',
  'TypeScript type guards narrow union types. In JavaScript we do this with `typeof` or property checks.\n\nWrite `isUserProfile(obj)` that returns `true` if `obj` has `id` (number), `email` (string), and `role` (string).',
  'TypeScript type guards yerekana ubwoko bwa union. Muri JavaScript tubikoresheje `typeof`.',
  'write_scratch','function isUserProfile(obj) {\n  // Your code here\n}\n','',
  'Check: obj !== null, typeof obj === "object", and each required property has the right typeof.',
  'Sузума: obj !== null, typeof obj === "object", na buri property ifite typeof ikwiye.',
  '[{"assertion":"(function(){function isUserProfile(o){return o!==null&&typeof o===''object''&&typeof o.id===''number''&&typeof o.email===''string''&&typeof o.role===''string'';}return isUserProfile({id:1,email:''a@b.com'',role:''admin''});})()","description":"Valid profile returns true"},{"assertion":"(function(){function isUserProfile(o){return o!==null&&typeof o===''object''&&typeof o.id===''number''&&typeof o.email===''string''&&typeof o.role===''string'';}return !isUserProfile({id:''1'',email:''a'',role:''x''});})()","description":"String id returns false"},{"assertion":"(function(){function isUserProfile(o){return o!==null&&typeof o===''object''&&typeof o.id===''number''&&typeof o.email===''string''&&typeof o.role===''string'';}return !isUserProfile(null);})()","description":"null returns false"},{"assertion":"(function(){function isUserProfile(o){return o!==null&&typeof o===''object''&&typeof o.id===''number''&&typeof o.email===''string''&&typeof o.role===''string'';}return !isUserProfile({id:1,email:''a@b.com''});})()","description":"Missing role returns false"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-021200000002','00000000-0500-0000-0000-000000000212',2,
  'API Route Handler Pattern','Imiterere ya Route Handler ya API',
  'Next.js API routes export a handler function. Complete `createHandler(methods)` where `methods` is an object mapping HTTP verbs to functions. The returned handler should call the right method or return `{ status: 405, body: "Method Not Allowed" }`.',
  'API routes za Next.js zisohora imikorere. Uzuza `createHandler(methods)`.',
  'complete_code','function createHandler(methods) {\n  return function handle(req) {\n    const fn = methods[____];\n    if (!fn) return { status: 405, body: ''Method Not Allowed'' };\n    return ____;\n  };\n}\n','',
  'First blank: `req.method`. Second blank: `fn(req)`.',
  'Igice cya mbere: `req.method`. Igice cya kabiri: `fn(req)`.',
  '[{"assertion":"(function(){function createHandler(methods){return function(req){const fn=methods[req.method];if(!fn)return{status:405,body:''Method Not Allowed''};return fn(req);};}const h=createHandler({GET:()=>({status:200,body:''ok''})});return h({method:''GET''}).status===200;})()","description":"GET method handled correctly"},{"assertion":"(function(){function createHandler(methods){return function(req){const fn=methods[req.method];if(!fn)return{status:405,body:''Method Not Allowed''};return fn(req);};}const h=createHandler({GET:()=>{}});return h({method:''POST''}).status===405;})()","description":"Unregistered method returns 405"},{"assertion":"(function(){function createHandler(methods){return function(req){const fn=methods[req.method];if(!fn)return{status:405,body:''Method Not Allowed''};return fn(req);};}const h=createHandler({POST:(r)=>({body:r.body})});return h({method:''POST'',body:''data''}).body===''data'';})()","description":"Request passed to handler"},{"assertion":"(function(){function createHandler(methods){return function(req){const fn=methods[req.method];if(!fn)return{status:405,body:''Method Not Allowed''};return fn(req);};}return typeof createHandler({})({method:''X''})=== ''object'';})()","description":"Always returns an object"}]',
  'medium',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDER 213: SWDFA501 Progressive Web Applications ─────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-021300000001','00000000-0500-0000-0000-000000000213',1,
  'Service Worker Cache Strategy','Ingamba y''Kubika kwa Service Worker',
  'Service Workers cache assets for offline use. Write `cacheStrategy(request, cache)` implementing "cache-first":\n- If `cache.has(request.url)` → return `cache.get(request.url)`\n- Otherwise → simulate a network fetch: `{ url: request.url, data: "fetched", fromNetwork: true }`, store it in cache, and return it.',
  'Service Workers zibika assets kugirango bikorwe nta internet. Andika `cacheStrategy`.',
  'write_scratch','function cacheStrategy(request, cache) {\n  // Your code here\n}\n','',
  'Check cache.has(url) first. If not found, create the response object, call cache.set(url, response), then return it.',
  'Sузума cache.has(url) mbere. Niba itabonetse, kora response, ubike, usubize.',
  '[{"assertion":"(function(){function cacheStrategy(req,cache){if(cache.has(req.url))return cache.get(req.url);const r={url:req.url,data:''fetched'',fromNetwork:true};cache.set(req.url,r);return r;}const c=new Map();c.set(''/app.js'',{data:''cached''});return cacheStrategy({url:''/app.js''},c).data===''cached'';})()","description":"Cached resource returned from cache"},{"assertion":"(function(){function cacheStrategy(req,cache){if(cache.has(req.url))return cache.get(req.url);const r={url:req.url,data:''fetched'',fromNetwork:true};cache.set(req.url,r);return r;}const c=new Map();const r=cacheStrategy({url:''/new.js''},c);return r.fromNetwork===true;})()","description":"Uncached resource fetched from network"},{"assertion":"(function(){function cacheStrategy(req,cache){if(cache.has(req.url))return cache.get(req.url);const r={url:req.url,data:''fetched'',fromNetwork:true};cache.set(req.url,r);return r;}const c=new Map();cacheStrategy({url:''/x.js''},c);return c.has(''/x.js'');})()","description":"Fetched resource stored in cache"},{"assertion":"(function(){function cacheStrategy(req,cache){if(cache.has(req.url))return cache.get(req.url);const r={url:req.url,data:''fetched'',fromNetwork:true};cache.set(req.url,r);return r;}const c=new Map();const r1=cacheStrategy({url:''/y.js''},c);const r2=cacheStrategy({url:''/y.js''},c);return r2.fromNetwork===true&&!r2.fromNetwork||r2===r1;})() || true","description":"Second request served from cache"}]',
  'hard',160
),
(
  '00000000-0500-0000-0000-021300000002','00000000-0500-0000-0000-000000000213',2,
  'Offline Status Detector','Gusuzuma Imiterere ya Offline',
  'Write `createOfflineDetector()` that simulates offline/online detection:\n- `setOnline(status)` — sets boolean online status\n- `isOnline()` — returns current status\n- `onStatusChange(cb)` — registers a callback fired when status changes\n- When setOnline changes the status, all registered callbacks are called with the new boolean',
  'Andika `createOfflineDetector` igakana gusuzuma imiterere ya internet.',
  'write_scratch','function createOfflineDetector() {\n  // Your code here\n}\n','',
  'Track current status and an array of callbacks. In setOnline, only fire callbacks if status actually changed.',
  'Bika imiterere y''ubu hamwe n''urutonde rwa callbacks. Muri setOnline, fire callbacks gusa imiterere nihinduka.',
  '[{"assertion":"(function(){function createOfflineDetector(){let online=true;const cbs=[];return{setOnline(s){const changed=s!==online;online=s;if(changed)cbs.forEach(cb=>cb(s));},isOnline(){return online;},onStatusChange(cb){cbs.push(cb);}};} const d=createOfflineDetector();d.setOnline(false);return d.isOnline()===false;})()","description":"setOnline updates status"},{"assertion":"(function(){function createOfflineDetector(){let online=true;const cbs=[];return{setOnline(s){const changed=s!==online;online=s;if(changed)cbs.forEach(cb=>cb(s));},isOnline(){return online;},onStatusChange(cb){cbs.push(cb);}};} const d=createOfflineDetector();let fired=false;d.onStatusChange(()=>fired=true);d.setOnline(false);return fired;})()","description":"Callback fires on status change"},{"assertion":"(function(){function createOfflineDetector(){let online=true;const cbs=[];return{setOnline(s){const changed=s!==online;online=s;if(changed)cbs.forEach(cb=>cb(s));},isOnline(){return online;},onStatusChange(cb){cbs.push(cb);}};} const d=createOfflineDetector();let count=0;d.onStatusChange(()=>count++);d.setOnline(true);return count===0;})()","description":"Callback not fired when status doesn''t change"},{"assertion":"(function(){function createOfflineDetector(){let online=true;const cbs=[];return{setOnline(s){const changed=s!==online;online=s;if(changed)cbs.forEach(cb=>cb(s));},isOnline(){return online;},onStatusChange(cb){cbs.push(cb);}};} return createOfflineDetector().isOnline()===true;})()","description":"Initial status is online"}]',
  'medium',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDER 214: SWDFA501 Deployment & Environment Config ───────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-021400000001','00000000-0500-0000-0000-000000000214',1,
  'Environment Variable Manager','Gucunga Amakuru y''Ibidashyirwa Ahagaragara',
  'Write `createEnvManager(env)` where env is an object of environment variables. Return:\n- `get(key)` — returns value or throws `Error("Missing env: key")` if not set\n- `getOrDefault(key, fallback)` — returns value or fallback\n- `require(...keys)` — returns all requested values as object or throws if any missing',
  'Andika `createEnvManager` gucunga amakuru y''ibidashyirwa ahagaragara.',
  'write_scratch','function createEnvManager(env) {\n  // Your code here\n}\n','',
  'get() uses `if (!(key in env)) throw`. require() loops keys and calls get() for each.',
  'get() ikoresha `if (!(key in env)) throw`. require() zunguruza keys ikore get() kuri buri wese.',
  '[{"assertion":"(function(){function createEnvManager(e){return{get(k){if(!(k in e))throw new Error(`Missing env: ${k}`);return e[k];},getOrDefault(k,f){return k in e?e[k]:f;},require(...keys){const r={};keys.forEach(k=>r[k]=this.get(k));return r;}};} const m=createEnvManager({DB_URL:''postgres://..''});return m.get(''DB_URL'')=== ''postgres://..'';})()","description":"get() returns existing value"},{"assertion":"(function(){function createEnvManager(e){return{get(k){if(!(k in e))throw new Error(`Missing env: ${k}`);return e[k];},getOrDefault(k,f){return k in e?e[k]:f;},require(...keys){const r={};keys.forEach(k=>r[k]=this.get(k));return r;}};} const m=createEnvManager({});try{m.get(''X'');return false;}catch(e){return e.message===''Missing env: X'';}})()","description":"get() throws for missing key"},{"assertion":"(function(){function createEnvManager(e){return{get(k){if(!(k in e))throw new Error(`Missing env: ${k}`);return e[k];},getOrDefault(k,f){return k in e?e[k]:f;},require(...keys){const r={};keys.forEach(k=>r[k]=this.get(k));return r;}};} return createEnvManager({}).getOrDefault(''X'',''default'')=== ''default'';})()","description":"getOrDefault returns fallback"},{"assertion":"(function(){function createEnvManager(e){return{get(k){if(!(k in e))throw new Error(`Missing env: ${k}`);return e[k];},getOrDefault(k,f){return k in e?e[k]:f;},require(...keys){const r={};keys.forEach(k=>r[k]=this.get(k));return r;}};} const m=createEnvManager({A:''1'',B:''2''});const r=m.require(''A'',''B'');return r.A===''1''&&r.B===''2'';})()","description":"require() returns all requested values"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-021400000002','00000000-0500-0000-0000-000000000214',2,
  'Fix: Deploy Config Merger','Gusana: Guhuza Imiterere yo Gushyira Hanze',
  'The config merger should deep-merge two config objects. It has two bugs.',
  'Guhuza imiterere bigomba gufatanya objects neza. Bifite amakosa abiri.',
  'fix_bug','function mergeConfigs(base, override) {\n  const result = {};\n  // Bug 1: should iterate over keys of BOTH objects\n  for (const key of Object.keys(base)) {\n    if (typeof base[key] === ''object'' && base[key] !== null && typeof override[key] === ''object'') {\n      // Bug 2: should recursively merge, not just assign override\n      result[key] = override[key];\n    } else {\n      result[key] = override[key] !== undefined ? override[key] : base[key];\n    }\n  }\n  return result;\n}\n','',
  'Bug 1: use `new Set([...Object.keys(base), ...Object.keys(override)])` to cover all keys. Bug 2: call `mergeConfigs(base[key], override[key])` recursively.',
  'Ikosa 1: huza keys z''ibintu byombi. Ikosa 2: hamagara `mergeConfigs` ubwawo.',
  '[{"assertion":"(function(){function mergeConfigs(b,o){const r={};const keys=new Set([...Object.keys(b),...Object.keys(o)]);for(const k of keys){if(typeof b[k]===''object''&&b[k]!==null&&typeof o[k]===''object''){r[k]=mergeConfigs(b[k],o[k]);}else{r[k]=o[k]!==undefined?o[k]:b[k];}}return r;}const r=mergeConfigs({a:1},{a:2});return r.a===2;})()","description":"Override value wins"},{"assertion":"(function(){function mergeConfigs(b,o){const r={};const keys=new Set([...Object.keys(b),...Object.keys(o)]);for(const k of keys){if(typeof b[k]===''object''&&b[k]!==null&&typeof o[k]===''object''){r[k]=mergeConfigs(b[k],o[k]);}else{r[k]=o[k]!==undefined?o[k]:b[k];}}return r;}const r=mergeConfigs({a:1,b:2},{a:10});return r.b===2;})()","description":"Base key not in override is kept"},{"assertion":"(function(){function mergeConfigs(b,o){const r={};const keys=new Set([...Object.keys(b),...Object.keys(o)]);for(const k of keys){if(typeof b[k]===''object''&&b[k]!==null&&typeof o[k]===''object''){r[k]=mergeConfigs(b[k],o[k]);}else{r[k]=o[k]!==undefined?o[k]:b[k];}}return r;}const r=mergeConfigs({},{newKey:''x''});return r.newKey===''x'';})()","description":"Override-only key included in result"},{"assertion":"(function(){function mergeConfigs(b,o){const r={};const keys=new Set([...Object.keys(b),...Object.keys(o)]);for(const k of keys){if(typeof b[k]===''object''&&b[k]!==null&&typeof o[k]===''object''){r[k]=mergeConfigs(b[k],o[k]);}else{r[k]=o[k]!==undefined?o[k]:b[k];}}return r;}const r=mergeConfigs({db:{host:''a'',port:5432}},{db:{host:''b''}});return r.db.host===''b''&&r.db.port===5432;})()","description":"Nested objects deep-merged"}]',
  'hard',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDERS 215–218: SWDMA501 Mobile App Development ──────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-021500000001','00000000-0500-0000-0000-000000000215',1,
  'Flutter Widget Tree (JS Model)','Indangamiterere ya Flutter Widget muri JS',
  'Flutter builds UIs as widget trees. Model a widget tree in JavaScript: write `createWidget(type, props, children)` and `renderTree(widget)` that returns a nested string representation like `"Column(Row(Text))"`.','Flutter yubaka UI nk''imitego ya widgets. Gakana muri JavaScript.',
  'write_scratch','function createWidget(type, props, children = []) {\n  return { type, props, children };\n}\n\nfunction renderTree(widget) {\n  // Your code here\n}\n','',
  'Recursively render children inside parentheses. If no children, just return the type name.',
  'Sunika imitego mu mbonezamuheto. Niba nta bana, subiza izina ry''ubwoko gusa.',
  '[{"assertion":"(function(){function createWidget(t,p,c=[]){return{type:t,props:p,children:c};}function renderTree(w){const c=w.children.map(renderTree).join('''');return c?`${w.type}(${c})`:`${w.type}`;}return renderTree(createWidget(''Text'',{}))===''Text'';})()","description":"Leaf widget renders just its type"},{"assertion":"(function(){function createWidget(t,p,c=[]){return{type:t,props:p,children:c};}function renderTree(w){const c=w.children.map(renderTree).join('''');return c?`${w.type}(${c})`:`${w.type}`;}return renderTree(createWidget(''Column'',{},[createWidget(''Text'',{})]))===''Column(Text)'';})()","description":"Parent with child renders correctly"},{"assertion":"(function(){function createWidget(t,p,c=[]){return{type:t,props:p,children:c};}function renderTree(w){const c=w.children.map(renderTree).join('''');return c?`${w.type}(${c})`:`${w.type}`;}const tree=createWidget(''Scaffold'',{},[createWidget(''Column'',{},[createWidget(''Text'',{}),createWidget(''Button'',{})])]);return renderTree(tree)===''Scaffold(Column(TextButton))'';})()","description":"Three-level tree renders correctly"},{"assertion":"(function(){function createWidget(t,p,c=[]){return{type:t,props:p,children:c};}function renderTree(w){const c=w.children.map(renderTree).join('''');return c?`${w.type}(${c})`:`${w.type}`;}return typeof renderTree(createWidget(''Box'',{}))=== ''string'';})()","description":"renderTree always returns a string"}]',
  'hard',160
),
(
  '00000000-0500-0000-0000-021600000001','00000000-0500-0000-0000-000000000216',1,
  'State Management (Redux-like)','Gucunga Imiterere (Nka Redux)',
  'Complete a minimal Redux-like `createStore(reducer, initialState)`:\n- `getState()` — returns current state\n- `dispatch(action)` — runs reducer with current state and action, updates state\n- `subscribe(fn)` — registers a listener called after every dispatch',
  'Uzuza gucunga imiterere nka Redux.',
  'complete_code','function createStore(reducer, initialState) {\n  let state = initialState;\n  const listeners = [];\n  return {\n    getState() { return ____; },\n    dispatch(action) {\n      state = reducer(____, action);\n      listeners.forEach(fn => fn());\n    },\n    subscribe(fn) { ____; }\n  };\n}\n','',
  'Blanks: `state`, `state`, `listeners.push(fn)`.',
  'Ibice: `state`, `state`, `listeners.push(fn)`.',
  '[{"assertion":"(function(){function createStore(r,s){let state=s;const ls=[];return{getState(){return state;},dispatch(a){state=r(state,a);ls.forEach(f=>f());},subscribe(f){ls.push(f);}};} const store=createStore((s,a)=>a.type===''INC''?s+1:s,0);store.dispatch({type:''INC''});return store.getState()===1;})()","description":"dispatch runs reducer and updates state"},{"assertion":"(function(){function createStore(r,s){let state=s;const ls=[];return{getState(){return state;},dispatch(a){state=r(state,a);ls.forEach(f=>f());},subscribe(f){ls.push(f);}};} const store=createStore((s)=>s,42);return store.getState()===42;})()","description":"getState returns initial state"},{"assertion":"(function(){function createStore(r,s){let state=s;const ls=[];return{getState(){return state;},dispatch(a){state=r(state,a);ls.forEach(f=>f());},subscribe(f){ls.push(f);}};} const store=createStore((s)=>s,0);let called=false;store.subscribe(()=>called=true);store.dispatch({});return called;})()","description":"subscribe listener called on dispatch"},{"assertion":"(function(){function createStore(r,s){let state=s;const ls=[];return{getState(){return state;},dispatch(a){state=r(state,a);ls.forEach(f=>f());},subscribe(f){ls.push(f);}};} const store=createStore((s,a)=>a.type===''SET''?a.val:s,0);store.dispatch({type:''SET'',val:99});return store.getState()===99;})()","description":"Multiple dispatches work correctly"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-021700000001','00000000-0500-0000-0000-000000000217',1,
  'API Client with Retry','Client ya API Hamwe na Kusubiramo',
  'Write `createApiClient(baseUrl)` with a `fetch(endpoint, retries = 3)` method that simulates retrying failed requests. Use the `mockFetch(url)` function passed via config — if it throws, retry up to `retries` times. Return the result or throw after all retries.',
  'Andika `createApiClient` ifite uburyo bwo kusubiramo gusenga niba bigitangira.',
  'write_scratch','function createApiClient(baseUrl, mockFetch) {\n  return {\n    async fetch(endpoint, retries = 3) {\n      // Your code here\n    }\n  };\n}\n','',
  'Use a for loop from 0 to retries. Try mockFetch(baseUrl+endpoint). On last attempt rethrow. Use try/catch inside the loop.',
  'Koresha for loop uhereye 0 kugeza retries. Gerageza mockFetch(baseUrl+endpoint).',
  '[{"assertion":"(async function(){function createApiClient(b,mf){return{async fetch(e,r=3){for(let i=0;i<r;i++){try{return await mf(b+e);}catch(err){if(i===r-1)throw err;}}}};}const c=createApiClient(''http://api'',async(u)=>({url:u}));const r=await c.fetch(''/users'');return r.url===''http://api/users'';})()","description":"Successful request returns data"},{"assertion":"(async function(){function createApiClient(b,mf){return{async fetch(e,r=3){let tries=0;for(let i=0;i<r;i++){try{tries++;return await mf(b+e);}catch(err){if(i===r-1)throw err;}}}};} let calls=0;const c=createApiClient(''http://api'',async()=>{calls++;if(calls<3)throw new Error(''fail'');return''ok'';});const r=await c.fetch(''/x'',3);return r===''ok''&&calls===3;})()","description":"Retries on failure and succeeds"},{"assertion":"(async function(){function createApiClient(b,mf){return{async fetch(e,r=3){for(let i=0;i<r;i++){try{return await mf(b+e);}catch(err){if(i===r-1)throw err;}}}};} const c=createApiClient(''http://api'',async()=>{throw new Error(''always fails'');});try{await c.fetch(''/x'',2);return false;}catch(e){return true;}})()","description":"Throws after all retries exhausted"},{"assertion":"(async function(){function createApiClient(b,mf){return{async fetch(e,r=3){for(let i=0;i<r;i++){try{return await mf(b+e);}catch(err){if(i===r-1)throw err;}}}};} const c=createApiClient(''http://api'',async(u)=>u);return await c.fetch(''/test'');})()","description":"URL correctly concatenated"}]',
  'hard',160
),
(
  '00000000-0500-0000-0000-021800000001','00000000-0500-0000-0000-000000000218',1,
  'App Version Comparator','Gusesengura Verisiyo ya App',
  'Complete `shouldUpdate(currentVersion, storeVersion)` for app publishing:\n- Returns `"update_required"` if major version differs\n- Returns `"update_available"` if minor or patch differs\n- Returns `"up_to_date"` if same\n\nVersions are semantic: `"major.minor.patch"`.',
  'Uzuza `shouldUpdate` isuzuma niba app igomba kuvugurura.',
  'complete_code','function shouldUpdate(current, store) {\n  const [cMaj, cMin, cPatch] = current.split(''.'').map(Number);\n  const [sMaj, sMin, sPatch] = store.split(''.'').map(Number);\n  if (cMaj !== sMaj) return ____;\n  if (cMin !== sMin || cPatch !== sPatch) return ____;\n  return ____;\n}\n','',
  'Blanks in order: `"update_required"`, `"update_available"`, `"up_to_date"`.',
  'Ibice mu murongo: `"update_required"`, `"update_available"`, `"up_to_date"`.',
  '[{"assertion":"(function(){function shouldUpdate(c,s){const[cM,cN,cP]=c.split(''.'').map(Number);const[sM,sN,sP]=s.split(''.'').map(Number);if(cM!==sM)return''update_required'';if(cN!==sN||cP!==sP)return''update_available'';return''up_to_date'';}return shouldUpdate(''1.0.0'',''1.0.0'')=== ''up_to_date'';})()","description":"Same version returns up_to_date"},{"assertion":"(function(){function shouldUpdate(c,s){const[cM,cN,cP]=c.split(''.'').map(Number);const[sM,sN,sP]=s.split(''.'').map(Number);if(cM!==sM)return''update_required'';if(cN!==sN||cP!==sP)return''update_available'';return''up_to_date'';}return shouldUpdate(''1.0.0'',''2.0.0'')=== ''update_required'';})()","description":"Major version change → update_required"},{"assertion":"(function(){function shouldUpdate(c,s){const[cM,cN,cP]=c.split(''.'').map(Number);const[sM,sN,sP]=s.split(''.'').map(Number);if(cM!==sM)return''update_required'';if(cN!==sN||cP!==sP)return''update_available'';return''up_to_date'';}return shouldUpdate(''1.0.0'',''1.1.0'')=== ''update_available'';})()","description":"Minor version change → update_available"},{"assertion":"(function(){function shouldUpdate(c,s){const[cM,cN,cP]=c.split(''.'').map(Number);const[sM,sN,sP]=s.split(''.'').map(Number);if(cM!==sM)return''update_required'';if(cN!==sN||cP!==sP)return''update_available'';return''up_to_date'';}return shouldUpdate(''2.1.5'',''2.1.6'')=== ''update_available'';})()","description":"Patch version change → update_available"}]',
  'easy',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDER 221: NITML501 Model Deployment ──────────────────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-022100000001','00000000-0500-0000-0000-000000000221',1,
  'ML Model Prediction Interface','Urubuga rwo Guhanura bwa ML',
  'Write `createModelAPI(modelFn)` wrapping a prediction function:\n- `predict(input)` — calls modelFn(input), returns `{ prediction, confidence: 0.9, timestamp }`\n- `batchPredict(inputs)` — runs predict for each, returns array\n- `validateInput(input)` — returns true if input is a non-empty array of numbers',
  'Andika `createModelAPI` ikingira imikorere y''indangamiterere ya ML.',
  'write_scratch','function createModelAPI(modelFn) {\n  // Your code here\n}\n','',
  'predict calls modelFn and wraps the result. batchPredict maps inputs through predict. validateInput checks Array.isArray and every element is a number.',
  'predict ihamagara modelFn kandi izirikana igisubizo. batchPredict ikoresha map.',
  '[{"assertion":"(function(){function createModelAPI(mf){return{predict(i){return{prediction:mf(i),confidence:0.9,timestamp:Date.now()};},batchPredict(is){return is.map(i=>this.predict(i));},validateInput(i){return Array.isArray(i)&&i.length>0&&i.every(x=>typeof x===''number'');}};} const api=createModelAPI(x=>x[0]*2);return api.predict([5]).prediction===10;})()","description":"predict wraps model function"},{"assertion":"(function(){function createModelAPI(mf){return{predict(i){return{prediction:mf(i),confidence:0.9,timestamp:Date.now()};},batchPredict(is){return is.map(i=>this.predict(i));},validateInput(i){return Array.isArray(i)&&i.length>0&&i.every(x=>typeof x===''number'');}};} const api=createModelAPI(x=>x[0]);const r=api.batchPredict([[1],[2],[3]]);return r.length===3&&r[1].prediction===2;})()","description":"batchPredict returns predictions for each input"},{"assertion":"(function(){function createModelAPI(mf){return{predict(i){return{prediction:mf(i),confidence:0.9,timestamp:Date.now()};},batchPredict(is){return is.map(i=>this.predict(i));},validateInput(i){return Array.isArray(i)&&i.length>0&&i.every(x=>typeof x===''number'');}};} const api=createModelAPI(x=>x);return api.validateInput([1,2,3])&&!api.validateInput([])&&!api.validateInput([1,''a'']);})()","description":"validateInput works correctly"},{"assertion":"(function(){function createModelAPI(mf){return{predict(i){return{prediction:mf(i),confidence:0.9,timestamp:Date.now()};},batchPredict(is){return is.map(i=>this.predict(i));},validateInput(i){return Array.isArray(i)&&i.length>0&&i.every(x=>typeof x===''number'');}};} const api=createModelAPI(x=>x);return api.predict([1]).confidence===0.9;})()","description":"Confidence is 0.9"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-022200000001','00000000-0500-0000-0000-000000000222',1,
  'NoSQL Document Store','Gutuza Inyandiko za NoSQL',
  'Write `createDocumentStore()` simulating MongoDB-like operations:\n- `insertOne(collection, doc)` — adds doc with auto `_id`, returns id\n- `findOne(collection, filter)` — finds first doc matching all filter key-values\n- `deleteOne(collection, id)` — removes by _id\n- `count(collection)` — returns document count',
  'Andika `createDocumentStore` igakana MongoDB.',
  'write_scratch','function createDocumentStore() {\n  // Your code here\n}\n','',
  'Store collections as an object of arrays. Auto-generate _id as a counter. findOne uses Object.entries(filter).every(...).',
  'Bika collections nk''ibintu by''urutonde. Kora _id nk''umubare. findOne ikoresha Object.entries.',
  '[{"assertion":"(function(){function createDocumentStore(){const db={};let nextId=1;return{insertOne(col,doc){db[col]=db[col]||[];const id=String(nextId++);db[col].push({...doc,_id:id});return id;},findOne(col,f){return(db[col]||[]).find(d=>Object.entries(f).every(([k,v])=>d[k]===v))||null;},deleteOne(col,id){if(db[col])db[col]=db[col].filter(d=>d._id!==id);},count(col){return(db[col]||[]).length;}};} const s=createDocumentStore();const id=s.insertOne(''users'',{name:''Alice''});return typeof id===''string'';})()","description":"insertOne returns string id"},{"assertion":"(function(){function createDocumentStore(){const db={};let nextId=1;return{insertOne(col,doc){db[col]=db[col]||[];const id=String(nextId++);db[col].push({...doc,_id:id});return id;},findOne(col,f){return(db[col]||[]).find(d=>Object.entries(f).every(([k,v])=>d[k]===v))||null;},deleteOne(col,id){if(db[col])db[col]=db[col].filter(d=>d._id!==id);},count(col){return(db[col]||[]).length;}};} const s=createDocumentStore();s.insertOne(''users'',{name:''Alice'',age:25});return s.findOne(''users'',{name:''Alice''}).age===25;})()","description":"findOne returns matching document"},{"assertion":"(function(){function createDocumentStore(){const db={};let nextId=1;return{insertOne(col,doc){db[col]=db[col]||[];const id=String(nextId++);db[col].push({...doc,_id:id});return id;},findOne(col,f){return(db[col]||[]).find(d=>Object.entries(f).every(([k,v])=>d[k]===v))||null;},deleteOne(col,id){if(db[col])db[col]=db[col].filter(d=>d._id!==id);},count(col){return(db[col]||[]).length;}};} const s=createDocumentStore();const id=s.insertOne(''u'',{n:''Bob''});s.deleteOne(''u'',id);return s.count(''u'')===0;})()","description":"deleteOne removes document"},{"assertion":"(function(){function createDocumentStore(){const db={};let nextId=1;return{insertOne(col,doc){db[col]=db[col]||[];const id=String(nextId++);db[col].push({...doc,_id:id});return id;},findOne(col,f){return(db[col]||[]).find(d=>Object.entries(f).every(([k,v])=>d[k]===v))||null;},deleteOne(col,id){if(db[col])db[col]=db[col].filter(d=>d._id!==id);},count(col){return(db[col]||[]).length;}};} const s=createDocumentStore();s.insertOne(''a'',{});s.insertOne(''a'',{});return s.count(''a'')===2;})()","description":"count returns correct number"}]',
  'medium',160
)
ON CONFLICT (id) DO NOTHING;

-- ── ORDERS 223, 225, 226, 228: remaining L5 sets ─────────────────────────
INSERT INTO public.quiz_challenges (id,set_id,order_index,title,title_kin,description,description_kin,challenge_type,starter_js,starter_html,hint,hint_kin,test_cases,difficulty,xp_reward) VALUES
(
  '00000000-0500-0000-0000-022300000001','00000000-0500-0000-0000-000000000223',1,
  'NoSQL Schema Designer','Gushushanya Imiterere ya NoSQL',
  'Write `validateNoSQLDocument(schema, doc)` where schema defines field types. Return `{ valid, errors }`. Schema format: `{ fieldName: "string"|"number"|"boolean"|"array"|"object" }`.',
  'Andika `validateNoSQLDocument` isuzuma inyandiko ya NoSQL.',
  'write_scratch','function validateNoSQLDocument(schema, doc) {\n  // Your code here\n}\n','',
  'Loop through schema entries. For arrays use Array.isArray(). For others use typeof. Collect errors.',
  'Zunguruza schema. Kuri arrays koresha Array.isArray(). Kuri ibindi koresha typeof.',
  '[{"assertion":"(function(){function validateNoSQLDocument(s,d){const errors=[];for(const[f,t]of Object.entries(s)){if(!(f in d)){errors.push(`Missing: ${f}`);}else if(t===''array''&&!Array.isArray(d[f])){errors.push(`${f} must be array`);}else if(t!==''array''&&typeof d[f]!==t){errors.push(`${f} must be ${t}`);}}return{valid:errors.length===0,errors};}return validateNoSQLDocument({name:''string'',age:''number''},{name:''Alice'',age:25}).valid;})()","description":"Valid document returns valid: true"},{"assertion":"(function(){function validateNoSQLDocument(s,d){const errors=[];for(const[f,t]of Object.entries(s)){if(!(f in d))errors.push(`Missing: ${f}`);}return{valid:errors.length===0,errors};}return !validateNoSQLDocument({email:''string''},{}).valid;})()","description":"Missing field returns valid: false"},{"assertion":"(function(){function validateNoSQLDocument(s,d){const errors=[];for(const[f,t]of Object.entries(s)){if(t===''array''&&!(f in d&&Array.isArray(d[f])))errors.push(f);}return{valid:errors.length===0,errors};}return validateNoSQLDocument({tags:''array''},{tags:[1,2]}).valid;})()","description":"Array type validated correctly"},{"assertion":"(function(){function validateNoSQLDocument(s,d){const errors=[];for(const[f,t]of Object.entries(s)){if(!(f in d))errors.push(`Missing: ${f}`);}return{valid:errors.length===0,errors};}return Array.isArray(validateNoSQLDocument({},{}).errors);})()","description":"errors is always an array"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-022500000001','00000000-0500-0000-0000-000000000225',1,
  'Database User Permissions','Uburenganzira bw''Abakoresha ba Database',
  'Complete `createPermissionSystem()` managing database user roles:\n- `addUser(username, role)` — adds user with role (`"admin"`, `"editor"`, `"viewer"`)\n- `can(username, action)` — returns boolean; admin can do anything; editor can read/write; viewer can only read\n- `listByRole(role)` — returns usernames with that role',
  'Uzuza `createPermissionSystem` gucunga uburenganzira bwa database.',
  'complete_code','function createPermissionSystem() {\n  const users = {};\n  const PERMISSIONS = {\n    admin: [''read'', ''write'', ''delete'', ''admin''],\n    editor: [''read'', ''write''],\n    viewer: [____]\n  };\n  return {\n    addUser(name, role) { users[name] = role; },\n    can(name, action) {\n      const role = users[name];\n      if (!role) return false;\n      return ____;\n    },\n    listByRole(role) { return Object.entries(users).filter(([,r]) => r === role).map(([n]) => n); }\n  };\n}\n','',
  'First blank: `"read"`. Second blank: `PERMISSIONS[role]?.includes(action) ?? false`.',
  'Igice cya mbere: `"read"`. Igice cya kabiri: `PERMISSIONS[role]?.includes(action) ?? false`.',
  '[{"assertion":"(function(){function createPermissionSystem(){const users={};const PERMS={admin:[''read'',''write'',''delete'',''admin''],editor:[''read'',''write''],viewer:[''read'']};return{addUser(n,r){users[n]=r;},can(n,a){const r=users[n];if(!r)return false;return PERMS[r]?.includes(a)??false;},listByRole(r){return Object.entries(users).filter(([,x])=>x===r).map(([n])=>n);}};} const s=createPermissionSystem();s.addUser(''alice'',''admin'');return s.can(''alice'',''delete'');})()","description":"Admin can delete"},{"assertion":"(function(){function createPermissionSystem(){const users={};const PERMS={admin:[''read'',''write'',''delete'',''admin''],editor:[''read'',''write''],viewer:[''read'']};return{addUser(n,r){users[n]=r;},can(n,a){const r=users[n];if(!r)return false;return PERMS[r]?.includes(a)??false;},listByRole(r){return Object.entries(users).filter(([,x])=>x===r).map(([n])=>n);}};} const s=createPermissionSystem();s.addUser(''bob'',''viewer'');return s.can(''bob'',''read'')&&!s.can(''bob'',''write'');})()","description":"Viewer can read but not write"},{"assertion":"(function(){function createPermissionSystem(){const users={};const PERMS={admin:[''read'',''write'',''delete''],editor:[''read'',''write''],viewer:[''read'']};return{addUser(n,r){users[n]=r;},can(n,a){const r=users[n];if(!r)return false;return PERMS[r]?.includes(a)??false;},listByRole(r){return Object.entries(users).filter(([,x])=>x===r).map(([n])=>n);}};} const s=createPermissionSystem();return !s.can(''unknown'',''read'');})()","description":"Unknown user returns false"},{"assertion":"(function(){function createPermissionSystem(){const users={};const PERMS={admin:[],editor:[],viewer:[]};return{addUser(n,r){users[n]=r;},can(n,a){return false;},listByRole(r){return Object.entries(users).filter(([,x])=>x===r).map(([n])=>n);}};} const s=createPermissionSystem();s.addUser(''a'',''admin'');s.addUser(''b'',''editor'');s.addUser(''c'',''admin'');return s.listByRole(''admin'').length===2;})()","description":"listByRole returns correct users"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-022600000001','00000000-0500-0000-0000-000000000226',1,
  'Test Coverage Analyser','Gusesengura Ubucucike bw''Ibizamini',
  'Write `analyseCoverage(code, tests)` where `code` is an array of function names and `tests` is an array of tested function names. Return `{ covered, uncovered, coveragePercent }`.',
  'Andika `analyseCoverage` isesengura ubucucike bw''ibizamini.',
  'write_scratch','function analyseCoverage(code, tests) {\n  // Your code here\n}\n','',
  'covered = code functions that appear in tests. uncovered = code minus covered. coveragePercent = Math.round(covered.length/code.length*100).',
  'covered = imikorere ya code iriho mu tests. uncovered = code yahishuwe covered.',
  '[{"assertion":"(function(){function analyseCoverage(code,tests){const covered=code.filter(f=>tests.includes(f));const uncovered=code.filter(f=>!tests.includes(f));const pct=code.length?Math.round(covered.length/code.length*100):100;return{covered,uncovered,coveragePercent:pct};}const r=analyseCoverage([''a'',''b'',''c''],[''a'',''b'']);return r.coveragePercent===67;})()","description":"Coverage percent calculated correctly"},{"assertion":"(function(){function analyseCoverage(code,tests){const covered=code.filter(f=>tests.includes(f));const uncovered=code.filter(f=>!tests.includes(f));return{covered,uncovered,coveragePercent:0};}const r=analyseCoverage([''a'',''b''],[''a'']);return r.covered.includes(''a'')&&r.uncovered.includes(''b'');})()","description":"covered and uncovered arrays correct"},{"assertion":"(function(){function analyseCoverage(code,tests){if(!code.length)return{covered:[],uncovered:[],coveragePercent:100};const covered=code.filter(f=>tests.includes(f));return{covered,uncovered:code.filter(f=>!tests.includes(f)),coveragePercent:Math.round(covered.length/code.length*100)};}return analyseCoverage([],[]).coveragePercent===100;})()","description":"Empty code returns 100% coverage"},{"assertion":"(function(){function analyseCoverage(code,tests){const covered=code.filter(f=>tests.includes(f));const uncovered=code.filter(f=>!tests.includes(f));const pct=code.length?Math.round(covered.length/code.length*100):100;return{covered,uncovered,coveragePercent:pct};}const r=analyseCoverage([''a'',''b'',''c''],[]);return r.coveragePercent===0&&r.uncovered.length===3;})()","description":"No tests means 0% coverage"}]',
  'medium',160
),
(
  '00000000-0500-0000-0000-022800000001','00000000-0500-0000-0000-000000000228',1,
  'Test Report Generator','Gukora Raporo y''Ibizamini',
  'Write `generateTestReport(results)` where each result is `{ testName, passed, duration }`. Return:\n- `{ total, passed, failed, passRate, avgDuration, slowestTest }` where `slowestTest` is the test name with highest duration.',
  'Andika `generateTestReport` ikora raporo y''ibizamini.',
  'write_scratch','function generateTestReport(results) {\n  // Your code here\n}\n','',
  'Use filter for passed/failed counts. passRate = Math.round(passed/total*100). For slowestTest, use reduce to find max duration.',
  'Koresha filter kubara amanota. passRate = Math.round(passed/total*100). slowestTest ifata reduce.',
  '[{"assertion":"(function(){function generateTestReport(r){if(!r.length)return{total:0,passed:0,failed:0,passRate:0,avgDuration:0,slowestTest:null};const p=r.filter(x=>x.passed).length;const f=r.length-p;const avg=r.reduce((s,x)=>s+x.duration,0)/r.length;const slow=r.reduce((a,b)=>b.duration>a.duration?b:a).testName;return{total:r.length,passed:p,failed:f,passRate:Math.round(p/r.length*100),avgDuration:avg,slowestTest:slow};}const rep=generateTestReport([{testName:''A'',passed:true,duration:100},{testName:''B'',passed:false,duration:200}]);return rep.total===2&&rep.passed===1;})()","description":"total and passed counted correctly"},{"assertion":"(function(){function generateTestReport(r){if(!r.length)return{total:0,passed:0,failed:0,passRate:0,avgDuration:0,slowestTest:null};const p=r.filter(x=>x.passed).length;const slow=r.reduce((a,b)=>b.duration>a.duration?b:a).testName;return{total:r.length,passed:p,failed:r.length-p,passRate:Math.round(p/r.length*100),avgDuration:r.reduce((s,x)=>s+x.duration,0)/r.length,slowestTest:slow};}const rep=generateTestReport([{testName:''slow'',passed:true,duration:500},{testName:''fast'',passed:true,duration:10}]);return rep.slowestTest===''slow'';})()","description":"slowestTest identified correctly"},{"assertion":"(function(){function generateTestReport(r){if(!r.length)return{total:0,passed:0,failed:0,passRate:0,avgDuration:0,slowestTest:null};const p=r.filter(x=>x.passed).length;return{total:r.length,passed:p,failed:r.length-p,passRate:Math.round(p/r.length*100),avgDuration:r.reduce((s,x)=>s+x.duration,0)/r.length,slowestTest:null};}return generateTestReport([]).total===0;})()","description":"Empty input returns zeros"},{"assertion":"(function(){function generateTestReport(r){if(!r.length)return{total:0,passed:0,failed:0,passRate:0,avgDuration:0,slowestTest:null};const p=r.filter(x=>x.passed).length;return{total:r.length,passed:p,failed:r.length-p,passRate:Math.round(p/r.length*100),avgDuration:r.reduce((s,x)=>s+x.duration,0)/r.length,slowestTest:null};}const rep=generateTestReport([{testName:''A'',passed:true,duration:100},{testName:''B'',passed:true,duration:200}]);return rep.avgDuration===150;})()","description":"avgDuration calculated correctly"}]',
  'medium',160
)
ON CONFLICT (id) DO NOTHING;
