import LegalLayout, { type LegalSection } from './LegalLayout';

const sections: LegalSection[] = [
  {
    id: 'section-1',
    heading: '1. Who provides this platform',
    content: (
      <p>
        EduCode Rwanda is an educational platform developed and operated by Mitali Bela as a capstone
        research project for the degree of BSc. Software Engineering at African Leadership University.
        The developer is the data controller for the purposes of Law No. 058/2021 of 13/10/2021
        relating to the protection of personal data and privacy. The platform is not a commercial
        product and is not operated by any school, by the Rwanda TVET Board, or by African Leadership
        University.
      </p>
    ),
  },
  {
    id: 'section-2',
    heading: '2. Who may use the platform',
    content: (
      <p>
        The platform is intended for students and teachers in Rwandan Technical and Vocational
        Education and Training institutions, and for independent learners. Where a user is below the
        age of majority, access is arranged through the user&rsquo;s school, and the school acts as the
        institutional gatekeeper for participation. A student who does not wish to take part may say
        so and will not be disadvantaged in their coursework.
      </p>
    ),
  },
  {
    id: 'section-3',
    heading: '3. Licence granted to the user',
    content: (
      <p>
        The user is granted a personal, non-exclusive, non-transferable, revocable licence to access
        and use the platform for learning and teaching. The user may not resell access, may not
        attempt to extract the underlying model or training data, may not use automated means to
        scrape platform content, and may not use the platform to submit unlawful material or the
        personal data of other people.
      </p>
    ),
  },
  {
    id: 'section-4',
    heading: '4. Ownership of code written by the user',
    content: (
      <>
        <p style={{ marginBottom: 16 }}>
          Code that a user writes in the workspace remains the user&rsquo;s own work.
        </p>
        <p>
          By submitting code for feedback, the user grants the developer permission to process that
          code for the purpose of generating feedback, and to retain it in anonymised or aggregated
          form for research into common learner errors and for improving the platform&rsquo;s model.
          The user may ask for their submissions to be removed, as set out in Part B.
        </p>
      </>
    ),
  },
  {
    id: 'section-5',
    heading: '5. The nature of AI feedback and its limits',
    content: (
      <>
        <p style={{ marginBottom: 16 }}>
          Feedback is produced by an artificial intelligence model. The model can be wrong. It may
          produce an explanation that is incomplete, misleading, or incorrect, and it may on occasion
          generate code or syntax that does not work. Feedback is offered as a guide to help the
          learner reason toward their own solution, not as an authoritative answer.
        </p>
        <p style={{ marginBottom: 16 }}>
          The platform does not assign grades automatically. No feedback generated by the model
          determines a student&rsquo;s mark or progression without a teacher reviewing it. Marking
          decisions remain with the human teacher at all times.
        </p>
        <p>
          Users are encouraged to check the platform&rsquo;s explanations against their teacher,
          their course materials, and official documentation, and to raise any output that appears
          wrong with their teacher.
        </p>
      </>
    ),
  },
  {
    id: 'section-6',
    heading: '6. Academic integrity and assessment monitoring',
    content: (
      <>
        <p style={{ marginBottom: 16 }}>
          When a teacher sets an assessment in examination mode, the platform monitors the session
          for the duration of that assessment only. It records whether the user leaves the assessment
          tab, whether the browser loses focus, whether the fullscreen view is exited, and whether
          content is pasted into the editor. It submits the assessment automatically when the timer
          expires.
        </p>
        <p style={{ marginBottom: 16 }}>
          This monitoring is disclosed to students before an assessment begins. It applies only
          during a timed assessment and is not applied to ordinary lessons, challenges, or use of the
          tutor.
        </p>
        <p>
          Its purpose is to make assessment fair for every student, not to observe general behaviour.
        </p>
      </>
    ),
  },
  {
    id: 'section-7',
    heading: '7. Availability, warranty, and liability',
    content: (
      <p>
        The platform is provided on an as-is basis, without warranty of uninterrupted availability.
        It depends on third-party services and on an internet connection, and it may be unavailable
        at times. The developer is not liable for academic outcomes, for loss of unsaved work, or for
        reliance on model-generated feedback that turns out to be incorrect. This does not exclude
        any liability that cannot be excluded under Rwandan law.
      </p>
    ),
  },
  {
    id: 'section-8',
    heading: '8. Suspension and termination',
    content: (
      <p>
        The developer may suspend an account that is used to attack the platform, to harm other
        users, or to breach this agreement. A user may stop using the platform at any time and may
        request that their account be closed, as set out in Part B.
      </p>
    ),
  },
  {
    id: 'section-9',
    heading: '9. Governing law and changes',
    content: (
      <p>
        This agreement is governed by the laws of the Republic of Rwanda. If this agreement changes
        in a way that materially affects users, notice will be given on the platform before the
        change takes effect.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalLayout
      pageTitle="Terms of Service · EduCode Rwanda"
      eyebrow="Legal"
      title="End-User Licence Agreement"
      lede="This agreement governs your access to and use of the EduCode Rwanda platform."
      version="Version 1.0"
      effective="1 June 2026"
      lastReviewed="19 July 2026"
      sections={sections}
      crossLink={{ label: 'Privacy Policy (Part B →)', to: '/privacy' }}
    />
  );
}
